baseURL: 'https://gobuffalo.io/'
languageCode: en-us
title: The Buffalo Framework
defaultContentLanguage: en
params:
  goMinVersion: v1.16.0
outputs:
    home: ["HTML", "RSS", "JSON"]
languages:
  en:
    languageName: English
    languageCode: en-us
    title: üá¨üáß EN
    weight: 1
    params:
      copyRight: All rights reserved.
      logoCredits: >-
        Buffalo Gopher designed by [Ashley
        McNamara](https://twitter.com/ashleymcnamara) ‚Äî Original Gopher designed
        by Renee French
      documentation: "Documentation"
      tutorials: "Tutorials"
      support: "Support"
      troubleshooting: "Troubleshooting"
      searchButtonText: "Search..."
      searchPlaceholder: "Search the Buffalo docs"
      noResultsCopy: "We couldn't find any guides or documents with that term. Please try again. You can also visit the documentation site and navigate for more details."
      fromOurBlog: "From our blog"
      learnMore: "Learn more"
      readMore: "Read more"
      since: "Since"
    menu:
      top:
        - name: Documentation
          url: /documentation/
          weight: 3
        - name: Blog
          url: 'https://blog.gobuffalo.io'
          weight: 5
  fr:
    languageName: Fran√ßais
    languageCode: fr-fr
    title: üá´üá∑ FR
    weight: 2
    params:
      copyRight: Tous droits r√©serv√©s.
      logoCredits: >-
        Gopher Buffalo con√ßu par [Ashley
        McNamara](https://twitter.com/ashleymcnamara) ‚Äî Gopher originel con√ßu
        par Renee French.
      documentation: "Documentation"
      tutorials: "Tutoriels"
      support: "Support"
      troubleshooting: "D√©pannage"
      searchButtonText: "Rechercher..."
      searchPlaceholder: "Rechercher dans les documents Buffalo"
      noResultsCopy: "Nous n'avons trouv√© aucun guide ou document contenant ce terme. Veuillez r√©essayer. Vous pouvez √©galement visiter le site de documentation et naviguer pour plus de d√©tails."
      fromOurBlog: "De notre blog"
      learnMore: "Apprendre encore plus"
      readMore: "Lire la suite"
      since: "Depuis"
    menu:
      top:
        - name: Documentation
          url: /fr/documentation/
          weight: 3
        - name: Blog
          url: 'https://blog.gobuffalo.io'
          weight: 5
  es:
    languageName: Spanish
    languageCode: es-la
    title: üá™üá∏ ES
    weight: 3
    params:
      copyRight: Todos los derechos reservados.
      logoCredits: >-
        El Roedor de Buffalo fu√© dise√±ado por [Ashley
        McNamara](https://twitter.com/ashleymcnamara) ‚Äî El roedor original de Go fu√© dise√±ado por Renee French
      documentation: "Documentaci√≥n"
      tutorials: "Tutoriales"
      support: "Soporte"
      troubleshooting: "Soluci√≥n de problemas"
      searchButtonText: "Buscar..."
      searchPlaceholder: "Buscar en la documentaci√≥n de Buffalo"
      noResultsCopy: "No pudimos encontrar gu√≠as o documentos con ese t√©rmino. Int√©ntalo de nuevo. Tambi√©n puede visitar el sitio de documentaci√≥n y navegar para obtener m√°s detalles."
      fromOurBlog: "En nuestro Blog"
      learnMore: "Aprender M√°s"
      readMore: "Leer m√°s"
      since: "Desde"
    menu:
      top:
        - name: Documentaci√≥n
          url: /es/documentation/
          weight: 3
        - name: Blog
          url: 'https://blog.gobuffalo.io'
          weight: 5
  pt:
    languageName: Portugu√™s
    languageCode: pt-pt
    title: üáµüáπ PT
    weight: 
    params:
      copyRight: Todos direitos reservados.
      logoCredits: >-
        Gopher Buffalo desenhado por [Ashley
        McNamara](https://twitter.com/ashleymcnamara) ‚Äî Gopher Original desenhado
        por Renee French
      documentation: "Documenta√ß√£o"
      tutorials: "Aulas Individuais"
      support: "Apoiar"
      troubleshooting: "Resolu√ß√£o de problemas"
      searchButtonText: "Pesquisar..."
      searchPlaceholder: "Pesquisar a documenta√ß√£o do Buffalo"
      noResultsCopy: "N√≥s n√£o conseguimos encontrar quaisquer guias ou documentos com este termo. Por favor tente novamente. Tu podes tamb√©m visitar o s√≠tio da nossa documenta√ß√£o e navegar para obter mais detalhes."
      fromOurBlog: "A partir do nosso blogue"
      learnMore: "Aprenda mais"
      readMore: "Leia mais"
      since: "Desde"
    menu:
      top:
        - name: Documenta√ß√£o
          url: /pt/documentation/
          weight: 3
        - name: Blogue
          url: 'https://blog.gobuffalo.io'
          weight: 5
