baseURL: 'https://gobuffalo.io/'
languageCode: en-us
title: The Buffalo Framework
defaultContentLanguage: en
params:
  goMinVersion: v1.16.0
outputs:
    home: ["HTML", "RSS", "JSON"]
languages:
  en:
    languageName: English
    languageCode: en-us
    title: üá¨üáß EN
    weight: 1
    params:
      copyRight: Copyright ¬© 2022 Buffalo. All rights reserved.
      logoCredits: >-
        Buffalo Gopher designed by [Ashley
        McNamara](https://twitter.com/ashleymcnamara) ‚Äî Original Gopher designed
        by Renee French
      documentation: "Documentation"
      tutorials: "Tutorials"
      support: "Support"
      troubleshooting: "Troubleshooting"
      searchButtonText: "Search..."
      searchPlaceholder: "Search the Buffalo docs"
      noResultsCopy: "We couldn't find any guides or documents with that term. Please try again. You can also visit the documentation site and navigate for more details."
      fromOurBlog: "From our blog"
      learnMore: "Learn more"
      readMore: "Read more"
    menu:
      top:
        - name: Documentation
          url: /documentation/
          weight: 3
        - name: Blog
          url: 'https://blog.gobuffalo.io'
          weight: 5
        # - name: Store
        #   url: 'https://store.gobuffalo.io'
        #   weight: 6
  fr:
    languageName: Fran√ßais
    languageCode: fr-fr
    title: üá´üá∑ FR
    weight: 2
    params:
      copyRight: Copyright ¬© 2022 Buffalo. Tous droits r√©serv√©s.
      logoCredits: >-
        Gopher Buffalo con√ßu par [Ashley
        McNamara](https://twitter.com/ashleymcnamara) ‚Äî Gopher originel con√ßu
        par Renee French.
      documentation: "Documentation"
      tutorials: "Tutoriels"
      support: "Support"
      troubleshooting: "D√©pannage"
      searchButtonText: "Rechercher..."
      searchPlaceholder: "Rechercher dans les documents Buffalo"
      noResultsCopy: "Nous n'avons trouv√© aucun guide ou document contenant ce terme. Veuillez r√©essayer. Vous pouvez √©galement visiter le site de documentation et naviguer pour plus de d√©tails."
      fromOurBlog: "De notre blog"
      learnMore: "Apprendre encore plus"
      readMore: "Lire la suite"
    menu:
      top:
        - name: Documentation
          url: /fr/documentation/
          weight: 3
        - name: Blog
          url: 'https://blog.gobuffalo.io'
          weight: 5
        # - name: Boutique
        #   url: 'https://store.gobuffalo.io'
        #   weight: 6
  es:
    languageName: Spanish
    languageCode: es-la
    title: üá™üá∏ ES
    weight: 1
    params:
      copyRight: Copyright ¬© 2022 Buffalo. Todos los derechos reservados.
      logoCredits: >-
        El Roedor de Buffalo fu√© dise√±ado por [Ashley
        McNamara](https://twitter.com/ashleymcnamara) ‚Äî El roedor original de Go fu√© dise√±ado por Renee French
      documentation: "Documentaci√≥n"
      tutorials: "Tutoriales"
      support: "Soporte"
      troubleshooting: "Soluci√≥n de problemas"
      searchButtonText: "Buscar..."
      searchPlaceholder: "Buscarn en la documentaci√≥n de Buffalo"
      noResultsCopy: "No pudimos encontrar gu√≠as o documentos con ese t√©rmino. Int√©ntalo de nuevo. Tambi√©n puede visitar el sitio de documentaci√≥n y navegar para obtener m√°s detalles."
      fromOurBlog: "En nuestro Blog"
      learnMore: "Aprender Mas"
      readMore: "Leer m√°s"
    menu:
      top:
        - name: Documentaci√≥n
          url: /documentation/
          weight: 3
        - name: Blog
          url: 'https://blog.gobuffalo.io'
          weight: 5
