[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  branch = "development"

[prune]
  go-tests = true
  unused-packages = true

  # DO NOT DELETE
  [[prune.project]] # buffalo
    name = "github.com/gobuffalo/buffalo"
    unused-packages = false

  # DO NOT DELETE
  [[prune.project]] # buffalo
    name = "github.com/gobuffalo/pop"
    unused-packages = false
